name: "TwinSync Spot"
version: "1.1.0"
slug: "twinsync_spot"
description: "Does this match YOUR definition? Compare camera snapshots to YOUR description of how a space should look."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:eye
hassio_api: true
homeassistant_api: true
watchdog: true
stage: stable
